function createfigure(X1, Y1, Z1, TitleText, ObstaclePos)
%CREATEFIGURE(X1,Y1,Z1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Z1:  vector of z data

%  Auto-generated by MATLAB on 02-Dec-2014 10:04:08

% Create figure
figure1 = figure();

% Create axes
axes1 = axes('Parent',figure1,'FontWeight','bold','FontSize',12,...
    'FontName','Arial');
view(axes1,[45 14]);
grid(axes1,'on');
hold(axes1,'all');
axis([-2, 3, -2.5, -0.5, 0,2])
axis equal

% Create plot3
plot3(X1,Y1,Z1,'Marker','*','LineStyle','none');

if (ObstaclePos ~= [0 0 0])
    Z = zeros(1,100);
    Y = Z;
    X = linspace(-1,1,100);
    hold on
    plot3(X+ObstaclePos(1), Y + ObstaclePos(3), Z+ObstaclePos(2),'Marker','o','LineStyle','none', 'color', 'red')
    hold off
end


% Create title
title({TitleText},'FontWeight','bold','FontSize',14,...
    'FontName','Arial');

% Create xlabel
xlabel('X (m)','FontWeight','bold','FontSize',12,'FontName','Arial');

% Create ylabel
ylabel('Y (m)','FontWeight','bold','FontSize',12,'FontName','Arial');

% Create zlabel
zlabel('Z (m)','FontWeight','bold','FontSize',12,'FontName','Arial');

